## Machine Learning Zoomcamp

# 1.7 Introduction to NumPy

    Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
 ** Comparison operations
 ** Logical operations
* Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\pc\\miniconda3\\Lib\\site-packages\\numpy\\__init__.py'>

# Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [44]:
a[2] = 10

In [45]:
a

array([ 0,  1, 10,  3,  4])

In [10]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [46]:
a[2]

np.int64(10)

Two more useful functions for creating arrays. arange creates a range of numbers - it works like the Python function range, except instead of an iterator it gives us a NumPy array. The last element is exclusive:

In [47]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

linspace creates an array of a given size filled with numbers evenly spaced between the first and the second parameter:

In [48]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

The first element is 0, the last is 100, and everything in between is filled in. With 11 elements the steps are nice round numbers - 0, 10, 20, and so on.

## Multi-dimensional arrays

In [11]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

We use the same zeros function, but now we specify the dimensions of the array: the first number is the number of rows, the second is the number of columns:

In [12]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [13]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
n[0, 1] = 20

In [15]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [16]:
n[1] = 20

In [17]:
n

array([[ 1, 20,  3],
       [20, 20, 20],
       [ 7,  8,  9]])

In [18]:
n[1, 0] = 20

In [19]:
n

array([[ 1, 20,  3],
       [20, 20, 20],
       [ 7,  8,  9]])

In [20]:
n[2] = [1, 1, 1]

In [21]:
n

array([[ 1, 20,  3],
       [20, 20, 20],
       [ 1,  1,  1]])

In [22]:
n[:, 2] = [0, 1, 2]

In [23]:
n

array([[ 1, 20,  0],
       [20, 20,  1],
       [ 1,  1,  2]])

If we pass only one index, we get an entire row:

In [49]:
n[2]

array([1, 1, 2])

We can rewrite the entire row too - the only condition is that the dimensions match. Let's make the last row all ones:

In [50]:

n[2] = [1, 1, 1]
n

array([[ 1, 20,  0],
       [20, 20,  1],
       [ 1,  1,  1]])

The same works for columns. To get a column we need to specify only the second index, but we cannot leave the first one empty - we put the colon operator there, meaning "all the rows":

In [51]:
n[:, 1]

array([20, 20,  1])

And we can assign to the column as well:

In [52]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [20, 20,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

NumPy can also generate arrays with random numbers. Let's generate a two-dimensional array with 5 rows and 2 columns:

In [53]:
np.random.rand(5, 2)

array([[0.20464863, 0.61927097],
       [0.29965467, 0.26682728],
       [0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515]])

This gives us an array with random numbers between 0 and 1, sampled from the standard uniform distribution. Every time we execute this cell, we get different numbers.

If we want to make the results reproducible - so that when you run this code you get the same numbers as I do - we can fix the random seed. These numbers are not really random, they are pseudorandom: they are generated by an algorithm, and we can set the seed of this generator. Then the sequence of numbers produced on my computer and on your computer will be the same:

In [24]:
np.random.seed(2)
# 100 * np.random.rand(5, 2)

In [25]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

And for random integers there is randint, where we specify the lowest number, the highest number (exclusive - so this gives values between 0 and 99) and the size:

In [26]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [55]:
np.random.seed(2)
100 * np.random.randn(5, 2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [27]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

## Element-wise operations

Now let's explain the multiplication we just did. Create an array first - np.arange(5) gives us numbers from 0 to 4:



In [28]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [59]:
b = 10 + (a * 2)

In [60]:
b

array([10, 12, 30, 16, 18])

In [61]:
b = (10 + (a * 2)) ** 2

In [62]:
b

array([100, 144, 900, 256, 324])

In [29]:
b = (10 + (a * 2)) ** 2 / 100

In [30]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [31]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

In [63]:
a + b

array([100, 145, 910, 259, 328])

In [64]:
a * b

array([   0,  144, 9000,  768, 1296])

In [65]:
a / b

array([0.        , 0.00694444, 0.01111111, 0.01171875, 0.01234568])

In [67]:
a - b

array([-100, -143, -890, -253, -320])

## Comparison operations

In [32]:
a

array([0, 1, 2, 3, 4])

In [33]:
a >= 2

array([False, False,  True,  True,  True])

In [34]:
a > 2

array([False, False, False,  True,  True])

In [35]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [36]:
a > b

array([False, False,  True,  True,  True])

In [37]:
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [38]:
a

array([0, 1, 2, 3, 4])

In [39]:
a.std()

np.float64(1.4142135623730951)

In [40]:
n.min()

np.int64(0)

In [41]:
n

array([[ 1, 20,  0],
       [20, 20,  1],
       [ 1,  1,  2]])

In [42]:
n.max()

np.int64(20)

In [71]:
a.sum()

np.int64(18)

In [73]:
a.mean()

np.float64(3.6)